# % ccm_modify_date: 2024-10-07 20:10:56 %
# % ccm_author: mpegg %
# % version: 23 %
# % ccm_repo: https://github.com/mpegg007/TermiteTowers.git %
# % ccm_branch: main %
# % ccm_object_id: .pre-commit-config.yaml:23 %
# % ccm_commit_id: dbaa495ea5fbbb2a2f55cea4e3491bace9eec020 %
# % ccm_commit_count: 23 %
# % ccm_last_commit_message: exclude update_keywords.py from hook %
# % ccm_last_commit_author: Matthew Pegg %
# % ccm_last_commit_date: 2024-10-07 19:52:23 -0400 %
# % ccm_file_last_modified: 2024-10-07 20:10:41 %
# % ccm_file_name: .pre-commit-config.yaml %
# % ccm_file_type: text/plain %
# % ccm_file_encoding: us-ascii %
# % ccm_file_eol: CRLF %
# repos:
#   - repo: local
#     hooks:
#       - id: copy-update-keywords
#         name: Copy update-keywords.sh to pre-commit hook
#         entry: cmd /c "copy /Y git-automation\\update-keywords.sh .git\\hooks\\pre-commit"
#         language: system
#         always_run: true
#         pass_filenames: falses