#!/usr/bin/env bash
# install-hooks.sh: install, repair or verify the CCM git hooks.
#
# v2 (git-automation/v2/) is the ACTIVE implementation.
# v1 (git-automation/enhanced-*.sh) is kept only as a rollback path.
#
# Two pitfalls this script exists to prevent:
#
#   1. Git silently ignores a hook that is not executable. No warning, no
#      error - the hook just never runs. Hence the chmod on v2's entry
#      points.
#
#   2. A SYMLINKED hook breaks dependency lookup. bash sets BASH_SOURCE[0]
#      to the path it was invoked with, so for .git/hooks/pre-commit ->
#      ../../git-automation/v2/pre-commit.sh, BASH_SOURCE[0] is the symlink.
#      The scripts derive SCRIPT_DIR from it, so SCRIPT_DIR resolves to
#      .git/hooks - where ccm-apply.sh, ccm-lib.sh and secret-scanner.sh do
#      not exist. A stub that execs the real file by absolute path keeps
#      BASH_SOURCE[0] pointing at the real script instead.
#
# Usage:
#   ./git-automation/install-hooks.sh            install / repair (v2)
#   ./git-automation/install-hooks.sh --verify   check only; non-zero exit if broken
#   ./git-automation/install-hooks.sh --v1       switch back to v1

set -euo pipefail

REPO_ROOT=$(git rev-parse --show-toplevel)
HOOKS_DIR="$REPO_ROOT/.git/hooks"
V2_DIR="$REPO_ROOT/git-automation/v2"
LOG_FILE="$HOME/log/$(basename "$REPO_ROOT")-enhanced-hooks.log"

V2_ENTRY_POINTS=(pre-commit post-commit secret-scanner)

usage() { sed -n '2,22p' "$0" | sed 's/^#\{1,\} \{0,1\}//'; }

# Write a hook stub that execs <target> (repo-relative) by absolute path.
# rm -f first: writing through a symlink would clobber the real script.
write_stub() {
    local stub="$1" target="$2"
    rm -f "$stub"
    {
        printf '%s\n' '#!/usr/bin/env bash'
        printf '%s\n' '# Generated by git-automation/install-hooks.sh - do not edit by hand.'
        printf '%s\n' 'set -euo pipefail'
        printf '%s\n' 'REPO_ROOT="$(git rev-parse --show-toplevel)"'
        printf 'exec "%s" "$@"\n' "\$REPO_ROOT/$target"
    } > "$stub"
    chmod 755 "$stub"
}

verify() {
    local rc=0 h e
    echo "v2 entry points:"
    for e in "${V2_ENTRY_POINTS[@]}"; do
        if [ -x "$V2_DIR/$e.sh" ]; then
            printf '  ok    v2/%s.sh executable\n' "$e"
        else
            printf '  FAIL  v2/%s.sh NOT executable - git would skip it\n' "$e"; rc=1
        fi
    done

    echo "installed hooks:"
    for h in pre-commit post-commit; do
        if [ -x "$HOOKS_DIR/$h" ]; then
            printf '  ok    .git/hooks/%s -> %s\n' "$h" \
                "$(grep -o 'git-automation/[^"]*' "$HOOKS_DIR/$h" | tail -1)"
        else
            printf '  FAIL  .git/hooks/%s missing or not executable\n' "$h"; rc=1
        fi
    done

    echo "v1 rollback path:"
    for h in pre-commit post-commit; do
        if [ -x "$HOOKS_DIR/$h.v1" ]; then
            printf '  ok    .git/hooks/%s.v1 -> %s\n' "$h" \
                "$(grep -o 'git-automation/[^"]*' "$HOOKS_DIR/$h.v1" | tail -1)"
        else
            printf '  WARN  .git/hooks/%s.v1 missing - no rollback path\n' "$h"
        fi
    done

    echo "runtime evidence:"
    if [ -f "$LOG_FILE" ] && grep -q 'V2 pre-commit started' "$LOG_FILE"; then
        printf '  ok    hook has executed; last run: %s\n' \
            "$(grep 'V2 pre-commit started' "$LOG_FILE" | tail -1 | sed 's/=== //; s/ ===//')"
    else
        printf '  WARN  no "V2 pre-commit started" in %s - hooks may never have run\n' "$LOG_FILE"
    fi
    return $rc
}

install_v2() {
    local e h
    for e in "${V2_ENTRY_POINTS[@]}"; do
        chmod 755 "$V2_DIR/$e.sh"
    done
    write_stub "$HOOKS_DIR/pre-commit"  "git-automation/v2/pre-commit.sh"
    write_stub "$HOOKS_DIR/post-commit" "git-automation/v2/post-commit.sh"
    for h in pre-commit post-commit; do
        [ -e "$HOOKS_DIR/$h.v1" ] || write_stub "$HOOKS_DIR/$h.v1" "git-automation/enhanced-$h.sh"
    done
    echo "Installed v2 hooks."
}

install_v1() {
    write_stub "$HOOKS_DIR/pre-commit"  "git-automation/enhanced-pre-commit.sh"
    write_stub "$HOOKS_DIR/post-commit" "git-automation/enhanced-post-commit.sh"
    echo "Switched .git/hooks to v1 (rollback)."
}

case "${1:-}" in
    ""|--install) install_v2; echo; verify ;;
    --verify)     verify ;;
    --v1)         install_v1; echo; verify ;;
    -h|--help)    usage ;;
    *)            echo "unknown option: $1" >&2; usage >&2; exit 2 ;;
esac
