# % ccm_modify_date: 2024-10-07 20:10:56 %
# % ccm_author: mpegg %
# % version: 20 %
# % ccm_repo: https://github.com/mpegg007/TermiteTowers.git %
# % ccm_branch: main %
# % ccm_object_id: sample.cmd:20 %
# % ccm_commit_id: dbaa495ea5fbbb2a2f55cea4e3491bace9eec020 %
# % ccm_commit_count: 8 %
# % ccm_last_commit_message: exclude update_keywords.py from hook %
# % ccm_last_commit_author: Matthew Pegg %
# % ccm_last_commit_date: 2024-10-07 19:52:23 -0400 %
# % ccm_file_last_modified: 2024-10-07 20:10:41 %
# % ccm_file_name: sample.cmd %
# % ccm_file_type: text/plain %
# % ccm_file_encoding: us-ascii %
# % ccm_file_eol: CRLF %
repos:
  - repo: local
    hooks:
      - id: update-keywords
        name: Update Keywords
        entry: git-automation/update-keywords.sh
        language: script
        files: \.(py|sh|bash|zsh|ksh|ps1|psm1|psd1|bat|cmd|yaml)$
        stages: [pre-commit]
        