-- TermiteTowers Continuous Code Management Header TEMPLATE
-- % ccm_modify_date: 2025-08-29 13:36:35 %
-- % ccm_author: mpegg %
-- % ccm_author_email: mpegg@hotmail.com %
-- % ccm_repo: https://github.com/mpegg007/TermiteTowers.git %
-- % ccm_branch: main %
-- % ccm_object_id: tf-test.tf:0 %
-- % ccm_commit_id: unknown %
-- % ccm_commit_count: 0 %
-- % ccm_commit_message: unknown %
-- % ccm_commit_author: unknown %
-- % ccm_commit_email: unknown %
-- % ccm_commit_date: 1970-01-01 00:00:00 +0000 %
-- % ccm_file_last_modified: 2025-08-29 13:36:36 %
-- % ccm_file_name: tf-test.tf %
-- % ccm_file_type: text/plain %
-- % ccm_file_encoding: us-ascii %
-- % ccm_file_eol: CRLF %
-- % ccm_path: tf-test.tf %
-- % ccm_blob_sha: a197d20e64e279ec3fcaf875feffee1f8a19b2a9 %
-- % ccm_exec: no %
-- % ccm_size: 871 %
-- % ccm_tag:  %
-- tt-ccm.header.end

resource "x" "y" {}
