# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
#  TermiteTowers Continuous Code Management Header TEMPLATE --- %ccm_git_header_start:  %
#  %ccm_git_repo: TermiteTowers %
#  %ccm_git_branch: dev1 %
#  %ccm_git_object_id: infra/docker/eso-dev1.yml:113 %
#  %ccm_git_author: mpegg %
#  %ccm_git_author_email: mpegg@hotmail.com %
#  %ccm_git_blob_sha: 9692dc22e6997d552487f0eda08b75499af2edeb %
#  %ccm_git_commit_id: 8b186f9039f2b3f1503219473a1e2de120c993d1 %
#  %ccm_git_commit_count: 113 %
#  %ccm_git_commit_date: 2025-10-30 12:44:42 -0400 %
#  %ccm_git_commit_author: mpegg %
#  %ccm_git_commit_email: mpegg@hotmail.com %
#  %ccm_git_commit_message: commen block updates %
#  %ccm_git_modify_date: 2025-10-30 12:44:43 %
#  %ccm_git_file_last_modified: 2025-10-30 12:44:43 %
#  %ccm_git_file_name: eso-dev1.yml %
#  %ccm_git_path: infra/docker/eso-dev1.yml %
#  %ccm_git_language_mode: yaml %
#  %ccm_git_file_type: text/plain %
#  %ccm_git_file_encoding: us-ascii %
#  %ccm_git_file_eol: CRLF %
#  %ccm_git_exec: no %
#  %ccm_git_size: 646 %
#  TermiteTowers Continuous Code Management Header TEMPLATE --- %ccm_git_header_end:  %  
# %git_commit_history: adding secret-service % 
# %git_commit_history: docker updates % 
name: eso-dev1
services:
  eso:
    image: eso/eso:latest
    container_name: eso-dev1
    restart: unless-stopped
    ports:
      - "0.0.0.0:3520:3000"
    env_file:
      - ./env/eso.env
    volumes:
      - /mnt/ai_storage/eso/data:/app/data
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "5"
    networks:
      - app-services-net-dev1
# Docker external network definition
networks:
  secret-service-net-dev1:
    external: true
