# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
#  TermiteTowers Continuous Code Management Header TEMPLATE --- %ccm_git_header_start:  %
#  %ccm_git_repo: TermiteTowers %
#  %ccm_git_branch: dev1 %
#  %ccm_git_object_id: infra/docker/esphome-dev1.yml:121 %
#  %ccm_git_author: mpegg %
#  %ccm_git_author_email: mpegg@hotmail.com %
#  %ccm_git_blob_sha: e8767e0d7b503891ffecbb23193910848a76b5b8 %
#  %ccm_git_commit_id: 4a1cbe1072eb42723822f202e3fcd45247e1aa03 %
#  %ccm_git_commit_count: 121 %
#  %ccm_git_commit_date: 2025-11-30 12:26:01 -0500 %
#  %ccm_git_commit_author: mpegg %
#  %ccm_git_commit_email: mpegg@hotmail.com %
#  %ccm_git_commit_message: cleanup %
#  %ccm_git_modify_date: 2025-11-30 12:26:17 %
#  %ccm_git_file_last_modified: 2025-11-30 12:26:17 %
#  %ccm_git_file_name: esphome-dev1.yml %
#  %ccm_git_path: infra/docker/esphome-dev1.yml %
#  %ccm_git_language_mode: yaml %
#  %ccm_git_file_type: text/plain %
#  %ccm_git_file_encoding: us-ascii %
#  %ccm_git_file_eol: CRLF %
#  %ccm_git_exec: no %
#  %ccm_git_size: 502 %
#  TermiteTowers Continuous Code Management Header TEMPLATE --- %ccm_git_header_end:  %  
# %git_commit_history: november changes % 
name: esphome-dev1

services:
  esphome:
    image: esphome/esphome:latest
    container_name: esphome-dev1
    restart: unless-stopped
    network_mode: host
    #ports:
    #  - "0.0.0.0:3320:6052"
    volumes:
      - /home/mpegg-adm/source/TermiteTowers/hams/esphome:/config
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "5"

