# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
#  TermiteTowers Continuous Code Management Header TEMPLATE --- %ccm_git_header_start:  %
#  %ccm_git_repo: TermiteTowers %
#  %ccm_git_branch: dev1 %
#  %ccm_git_object_id: unknown %
#  %ccm_git_author: mpegg %
#  %ccm_git_author_email: mpegg@hotmail.com %
#  %ccm_git_blob_sha: 085dd6f8e23e81e877d0a8854c54df2fc42d9131 %
#  %ccm_git_commit_id: unknown %
#  %ccm_git_commit_count: unknown %
#  %ccm_git_commit_date: unknown %
#  %ccm_git_commit_author: unknown %
#  %ccm_git_commit_email: unknown %
#  %ccm_git_commit_message: unknown %
#  %ccm_git_modify_date: 2026-02-07 15:39:24 %
#  %ccm_git_file_last_modified: 2026-02-07 15:39:24 %
#  %ccm_git_file_name: mealie-dev1.yml %
#  %ccm_git_path: infra/docker/mealie-dev1.yml %
#  %ccm_git_language_mode: yaml %
#  %ccm_git_file_type: text/plain %
#  %ccm_git_file_encoding: us-ascii %
#  %ccm_git_file_eol: CRLF %
#  %ccm_git_exec: no %
#  %ccm_git_size: 741 %
#  TermiteTowers Continuous Code Management Header TEMPLATE --- %ccm_git_header_end:  %  
# %git_commit_history: 2025-11-30 mpegg  cleanup  % 
# %git_commit_history: docker updates % 
# password bradley1

name: mealie-dev1

services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: mealie-dev1
    restart: always
    ports:
      - "3301:9000"  # Correct port mapping for Mealie
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - BASE_URL=http://mealie.termitetowers.ca
      # Add other Mealie environment variables as needed
    networks:
      - app-services-net-dev1
    volumes:
      - /mnt/ai_storage/docker/mealie-data:/app/data
networks:
  app-services-net-dev1:
    external: true
