# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
# TermiteTowers Continuous Code Management Header TEMPLATE --- %ccm_git_header_start:  %
#  %ccm_git_repo: TermiteTowers %
#  %ccm_git_branch: dev1 %
#  %ccm_git_object_id: infra/docker/networks-dev2.yml:171 %
#  %ccm_git_author: mpegg %
#  %ccm_git_author_email: mpegg@hotmail.com %
#  %ccm_git_blob_sha: c80b20701467fda734f4c31d75e13a9edd9ebdef %
#  %ccm_git_commit_id: ee3eae8346d8982d0467de7e5b42579865765a24 %
#  %ccm_git_commit_count: 171 %
#  %ccm_git_commit_date: 2026-10-04 16:25:37 -0400 %
#  %ccm_git_commit_author: mpegg %
#  %ccm_git_commit_email: mpegg@hotmail.com %
#  %ccm_git_commit_message: cleanup %
#  %ccm_git_modify_date: 2026-10-04 16:25:37 %
#  %ccm_git_file_last_modified: 2025-10-29 16:47:10 %
#  %ccm_git_file_name: networks-dev2.yml %
#  %ccm_git_path: infra/docker/networks-dev2.yml %
#  %ccm_git_language_mode: yaml %
#  %ccm_git_file_type: text/plain %
#  %ccm_git_file_encoding: us-ascii %
#  %ccm_git_file_eol: CRLF %
#  %ccm_git_exec: yes %
#  %ccm_git_size: 937 %
#  TermiteTowers Continuous Code Management Header TEMPLATE --- %ccm_git_header_end:  %  
name: networks-dev2


networks:
  ai-services-net-dev2:
    driver: bridge
    ipam:
      config:
        - subnet: 10.20.0.0/20
          gateway: 10.20.0.1
  app-services-net-dev2:
    driver: bridge
    ipam:
      config:
        - subnet: 10.20.16.0/20
          gateway: 10.20.16.1
  core-infra-net-dev2:
    driver: bridge
    ipam:
      config:
        - subnet: 10.20.32.0/20
          gateway: 10.20.32.1
  docs-services-net-dev2:
    driver: bridge
    ipam:
      config:
        - subnet: 10.20.48.0/20
          gateway: 10.20.48.1
  monitor-apps-net-dev2:
    driver: bridge
    ipam:
      config:
        - subnet: 10.20.64.0/20
          gateway: 10.20.64.1
  productivity-apps-net-dev2:
    driver: bridge
    ipam:
      config:
        - subnet: 10.20.80.0/20
          gateway: 10.20.80.1
