# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
#  TermiteTowers Continuous Code Management Header TEMPLATE --- %ccm_git_header_start:  %
#  %ccm_git_repo: TermiteTowers %
#  %ccm_git_branch: dev1 %
#  %ccm_git_object_id: infra/docker/nextcloud-dev1.yml:132 %
#  %ccm_git_author: mpegg %
#  %ccm_git_author_email: mpegg@hotmail.com %
#  %ccm_git_blob_sha: ca5351eaeec1c0ecd233e880fa940b210c4569ec %
#  %ccm_git_commit_id: 6e67c9cb056223d2c5e30fd43ff735f0e43b37fb %
#  %ccm_git_commit_count: 132 %
#  %ccm_git_commit_date: 2026-02-07 16:19:47 -0500 %
#  %ccm_git_commit_author: mpegg %
#  %ccm_git_commit_email: mpegg@hotmail.com %
#  %ccm_git_commit_message: comment cleanup %
#  %ccm_git_modify_date: 2026-02-07 16:19:47 %
#  %ccm_git_file_last_modified: 2026-02-07 16:19:47 %
#  %ccm_git_file_name: nextcloud-dev1.yml %
#  %ccm_git_path: infra/docker/nextcloud-dev1.yml %
#  %ccm_git_language_mode: yaml %
#  %ccm_git_file_type: text/plain %
#  %ccm_git_file_encoding: us-ascii %
#  %ccm_git_file_eol: CRLF %
#  %ccm_git_exec: no %
#  %ccm_git_size: 797 %
#  TermiteTowers Continuous Code Management Header TEMPLATE --- %ccm_git_header_end:  %  
# %git_commit_history: 2026-02-07 mpegg  feb2026  % 

name: nextcloud-dev1
services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud-dev1
    restart: unless-stopped
    ports:
      - "0.0.0.0:3230:80"
    env_file:
      - ./env/nextcloud.env
    volumes:
      - /mnt/ai_storage/nextcloud/data:/var/www/html
      - /mnt/ai_storage/nextcloud/config:/var/www/html/config
      - /mnt/ai_storage/nextcloud/custom_apps:/var/www/html/custom_apps
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "5"
    networks:
      - app-services-net-dev1

networks:
  app-services-net-dev1:
    external: true
