# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
# TermiteTowers Continuous Code Management Header TEMPLATE
# % ccm_modify_date: 2025-08-31 14:31:46 %
# % ccm_author: mpegg %
# % ccm_author_email: mpegg@hotmail.com %
# % ccm_repo: https://github.com/mpegg007/TermiteTowers.git %
# % ccm_branch: dev1 %
# % ccm_object_id: infra/docker/tdarr-node-dev1.nvidia.yml:0 %
# % ccm_commit_id: unknown %
# % ccm_commit_count: 0 %
# % ccm_commit_message: unknown %
# % ccm_commit_author: unknown %
# % ccm_commit_email: unknown %
# % ccm_commit_date: 1970-01-01 00:00:00 +0000 %
# % ccm_file_last_modified: 2025-08-31 14:30:32 %
# % ccm_file_name: tdarr-node-dev1.nvidia.yml %
# % ccm_file_type: text/plain %
# % ccm_file_encoding: us-ascii %
# % ccm_file_eol: CRLF %
# % ccm_path: infra/docker/tdarr-node-dev1.nvidia.yml %
# % ccm_blob_sha: 191483e984fed94d51407f25e1f3d398c88d516e %
# % ccm_exec: no %
# % ccm_size: 2611 %
# % ccm_tag:  %
# tt-ccm.header.end
name: tdarr-dev1

services:
  tdarr-node:
    image: ghcr.io/haveagitgat/tdarr_node:latest
    container_name: tdarr-node-dev1
    network_mode: host
    environment:
      - TZ=${TZ:-America/Toronto}
      - PUID=${PUID:-2001}
      - PGID=${PGID:-1006}
      - nodeName=${TDARR_NODE_NAME:-monolith-node}
      - tdarrServerIP=${TDARR_SERVER_IP:-192.168.4.63}
      - tdarrServerPort=${TDARR_SERVER_PORT:-8266}
      - serverIP=${TDARR_SERVER_IP:-192.168.4.63}
      - serverPort=${TDARR_SERVER_PORT:-8266}
      - ffmpegVersion=static
      - npmPackages=false
      - videoProcessors=${TDARR_VIDEO_PROCS:-2}
      - nodeWorkerThreads=${TDARR_WORKERS:-2}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    gpus: all
    volumes:
      # If your Tdarr Server libraries are Windows paths (e.g. C:\\media.tt.omp),
      # mount the Windows share on this Linux host (e.g. /mnt/media via CIFS) and
      # add a Path Substitution in Server Settings: From C:\\media.tt.omp -> To /mnt/media
      - /mnt/media:/mnt/media:rw
      - /mnt/ai_storage/llm/logs/tdarr-node:/app/logs
      - /mnt/ai_storage/llm/configs/tdarr-node:/app/configs
      - /mnt/ai_storage/llm/cache/tdarr-node:/temp
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "5"

# Note: Prefer consolidated files under infra/tdarr-node/ with overlay:
#   docker compose -f infra/tdarr-node/tdarr-node-dev1.yml -f infra/tdarr-node/tdarr-node-dev1.nvidia.yml up -d
# Windows share guide: infra/docker/tdarr-node-windows-share.md
