# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
# TermiteTowers Continuous Code Management Header TEMPLATE
# % ccm_modify_date: 2025-08-31 14:31:46 %
# % ccm_author: mpegg %
# % ccm_author_email: mpegg@hotmail.com %
# % ccm_repo: https://github.com/mpegg007/TermiteTowers.git %
# % ccm_branch: dev1 %
# % ccm_object_id: infra/docker/tortoise-dev1.yml:0 %
# % ccm_commit_id: unknown %
# % ccm_commit_count: 0 %
# % ccm_commit_message: unknown %
# % ccm_commit_author: unknown %
# % ccm_commit_email: unknown %
# % ccm_commit_date: 1970-01-01 00:00:00 +0000 %
# % ccm_file_last_modified: 2025-08-31 14:30:32 %
# % ccm_file_name: tortoise-dev1.yml %
# % ccm_file_type: text/plain %
# % ccm_file_encoding: us-ascii %
# % ccm_file_eol: CRLF %
# % ccm_path: infra/docker/tortoise-dev1.yml %
# % ccm_blob_sha: 4b28d8aa930fdca9eb8ee092006739267acca67f %
# % ccm_exec: no %
# % ccm_size: 2596 %
# % ccm_tag:  %
# tt-ccm.header.end

services:
  tortoise-tts-dev1:
    image: pytorch/pytorch:2.1.0-cuda11.8-cudnn8-runtime
    container_name: tortoise-tts-dev1
    working_dir: /app
    user: "${UID_SVC:-2001}:${GID_TT_AI:-1006}"
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ../source:/app
      - ../models:/app/models
      - ../config:/app/config
      - ../logs:/app/logs
      - /mnt/ai_storage/models/huggingface:/cache/huggingface
      - /mnt/ai_storage/models/pip:/cache/pip
      - /mnt/ai_storage/models/torch:/cache/torch
      - /mnt/ai_storage/tortoise/voices:/app/voices
      - /mnt/ai_storage/tortoise/outputs:/app/outputs
    environment:
      - PYTHONUNBUFFERED=1
      - HF_HOME=/cache/huggingface
      - HF_HUB_ENABLE_PROGRESS_BARS=1
      - PIP_INDEX_URL=https://packages.termitetowers.ca/tt-devpi/cuda-stack/+simple
      - PIP_EXTRA_INDEX_URL=https://download.pytorch.org/whl/cu118
    command: >
      bash -lc "
        umask 002 &&
        export DEBIAN_FRONTEND=noninteractive &&
        chmod 1777 /tmp &&
        apt-get update &&
        apt-get install -y ffmpeg libsndfile1 git &&
        python3 -m pip install --upgrade pip &&
        python3 -m pip install --prefer-binary --verbose torch==2.1.0+cu118 torchvision==0.16.0+cu118 torchaudio==2.1.0 &&
        python3 -m pip install --prefer-binary --verbose -r requirements.txt &&
        python3 /app/tortoise-tts/do_tts.py --text \"${TEXT:-Hello world}\" --voice \"${VOICE:-hal}\"
      "
