# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
#  TermiteTowers Continuous Code Management Header TEMPLATE --- %ccm_git_header_start:  %
#  %ccm_git_repo: TermiteTowers %
#  %ccm_git_branch: dev1 %
#  %ccm_git_object_id: infra/docker/wiki-dev1.yml:121 %
#  %ccm_git_author: mpegg %
#  %ccm_git_author_email: mpegg@hotmail.com %
#  %ccm_git_blob_sha: 0a45dbe90e2f35aa91b17f007d99f5ffc0351de5 %
#  %ccm_git_commit_id: 4a1cbe1072eb42723822f202e3fcd45247e1aa03 %
#  %ccm_git_commit_count: 121 %
#  %ccm_git_commit_date: 2025-11-30 12:26:01 -0500 %
#  %ccm_git_commit_author: mpegg %
#  %ccm_git_commit_email: mpegg@hotmail.com %
#  %ccm_git_commit_message: cleanup %
#  %ccm_git_modify_date: 2025-11-30 12:27:09 %
#  %ccm_git_file_last_modified: 2025-11-30 12:27:09 %
#  %ccm_git_file_name: wiki-dev1.yml %
#  %ccm_git_path: infra/docker/wiki-dev1.yml %
#  %ccm_git_language_mode: yaml %
#  %ccm_git_file_type: text/plain %
#  %ccm_git_file_encoding: us-ascii %
#  %ccm_git_file_eol: CRLF %
#  %ccm_git_exec: no %
#  %ccm_git_size: 1195 %
#  TermiteTowers Continuous Code Management Header TEMPLATE --- %ccm_git_header_end:  %  
# %git_commit_history: docker updates % 
name: wiki-dev1

services:
  postgres:
    image: postgres:15
    container_name: wiki_postgres-dev1
    restart: unless-stopped
    user: "${UID_SVC:-2001}:${GID_TT_AI:-1006}"
    environment:
      POSTGRES_DB: wiki
      POSTGRES_USER: wikijs
      POSTGRES_PASSWORD: wikijsrocks
    volumes:
      - /mnt/ai_storage/wiki/postgres-data:/var/lib/postgresql/data
    command: ["bash","-lc","umask 002 && docker-entrypoint.sh postgres"]
    networks:
      - productivity-apps-net-dev1

  wikijs:
    image: ghcr.io/requarks/wiki:2
    container_name: wiki_app-dev1
    restart: unless-stopped
    user: "${UID_SVC:-2001}:${GID_TT_AI:-1006}"
    ports:
      - "3200:3000"
    environment:
      DB_TYPE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
    volumes:
      - /mnt/ai_storage/wiki/wikijs-data:/wiki/data
    depends_on:
      - postgres
    networks:
      - productivity-apps-net-dev1

# Docker external network definition
networks:
  productivity-apps-net-dev1:
    external: true
