#  TermiteTowers Continuous Code Management Header TEMPLATE --- %ccm_git_header_start:  %
#  %ccm_git_repo: TermiteTowers %
#  %ccm_git_branch: dev1 %
#  %ccm_git_object_id: infra/nginx/sites-available/docs.conf:125 %
#  %ccm_git_author: mpegg %
#  %ccm_git_author_email: mpegg@hotmail.com %
#  %ccm_git_blob_sha: ee3fbd5a8bbf0eec36bfca7003dbef3eddec8404 %
#  %ccm_git_commit_id: c1f5aa954a589e43600caffa76969fcd4a57b2f1 %
#  %ccm_git_commit_count: 125 %
#  %ccm_git_commit_date: 2025-12-15 10:05:29 -0500 %
#  %ccm_git_commit_author: mpegg %
#  %ccm_git_commit_email: mpegg@hotmail.com %
#  %ccm_git_commit_message: monday drop %
#  %ccm_git_modify_date: 2025-12-15 10:05:33 %
#  %ccm_git_file_last_modified: 2025-12-15 10:05:33 %
#  %ccm_git_file_name: docs.conf %
#  %ccm_git_path: infra/nginx/sites-available/docs.conf %
#  %ccm_git_language_mode: properties %
#  %ccm_git_file_type: text/plain %
#  %ccm_git_file_encoding: us-ascii %
#  %ccm_git_file_eol: CRLF %
#  %ccm_git_exec: no %
#  %ccm_git_size: 615 %
#  TermiteTowers Continuous Code Management Header TEMPLATE --- %ccm_git_header_end:  %  

server {
    listen 80;
    server_name docs.termitetowers.ca;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name docs.termitetowers.ca;

    ssl_certificate     /etc/letsencrypt/live/termitetowers.ca/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/termitetowers.ca/privkey.pem;

    location / {
        proxy_pass http://localhost:3210/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
