#  TermiteTowers Continuous Code Management Header TEMPLATE --- %ccm_git_header_start:  %
#  %ccm_git_repo: TermiteTowers %
#  %ccm_git_branch: dev1 %
#  %ccm_git_object_id: infra/nginx/sites-available/immich.conf:147 %
#  %ccm_git_author: mpegg %
#  %ccm_git_author_email: mpegg@hotmail.com %
#  %ccm_git_blob_sha: 2c13f78ef46b84838f158bcdad0aa0089dda728f %
#  %ccm_git_commit_id: 875dba4d1edbc0fb2fe425346b22faa6070d5e41 %
#  %ccm_git_commit_count: 147 %
#  %ccm_git_commit_date: 2026-06-10 17:10:31 -0400 %
#  %ccm_git_commit_author: mpegg %
#  %ccm_git_commit_email: mpegg@hotmail.com %
#  %ccm_git_commit_message: june bulk update %
#  %ccm_git_modify_date: 2026-06-10 17:10:32 %
#  %ccm_git_file_last_modified: 2026-05-31 17:35:31 %
#  %ccm_git_file_name: immich.conf %
#  %ccm_git_path: infra/nginx/sites-available/immich.conf %
#  %ccm_git_language_mode: nginx %
#  %ccm_git_file_type: text/plain %
#  %ccm_git_file_encoding: us-ascii %
#  %ccm_git_file_eol: CRLF %
#  %ccm_git_exec: no %
#  %ccm_git_size: 1460 %
#  TermiteTowers Continuous Code Management Header TEMPLATE --- %ccm_git_header_end:  %  
server {
    listen 3261 ssl;
    server_name pics.justanotherhuman.ca memorylab.analacres.ca;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # --- TLS hardening ---
    ssl_certificate     /etc/letsencrypt/live/memorylab.analacres.ca/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/memorylab.analacres.ca/privkey.pem;


    # allow large uploads for immich, and disable buffering for better performance with large files
    client_max_body_size 50000M;

    # disable buffering for better performance with large files, and to prevent nginx from interfering with Immich's own upload handling
    proxy_request_buffering off;

    # increase buffer size for large uploads, and to prevent nginx from interfering with Immich's own upload handling
    client_body_buffer_size 1024k;

    # set headers
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    # enable websockets for Immich's real-time features
    proxy_http_version 1.1;
    proxy_redirect     off;
    
    # set timeout
    proxy_read_timeout 600s;
    proxy_send_timeout 600s;

    # REQUIRED: Immich needs HTTP/1.1, no buffering, no CSP interference
    location / {
        proxy_pass http://127.0.0.1:3370/;

        proxy_set_header Update $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}