#  TermiteTowers Continuous Code Management Header TEMPLATE --- %ccm_git_header_start:  %
#  %ccm_git_repo: TermiteTowers %
#  %ccm_git_branch: dev1 %
#  %ccm_git_object_id: infra/nginx/sites-available/immich.conf:148 %
#  %ccm_git_author: mpegg %
#  %ccm_git_author_email: mpegg@hotmail.com %
#  %ccm_git_blob_sha: eb387da89ab6a0734fcf3741cde19a201f35aad8 %
#  %ccm_git_commit_id: a05e23946842d7f627bba10740a39e328f03d84e %
#  %ccm_git_commit_count: 148 %
#  %ccm_git_commit_date: 2026-06-14 10:37:47 -0400 %
#  %ccm_git_commit_author: mpegg %
#  %ccm_git_commit_email: mpegg@hotmail.com %
#  %ccm_git_commit_message: sunday updates %
#  %ccm_git_modify_date: 2026-06-14 10:37:48 %
#  %ccm_git_file_last_modified: 2026-06-14 10:37:48 %
#  %ccm_git_file_name: immich.conf %
#  %ccm_git_path: infra/nginx/sites-available/immich.conf %
#  %ccm_git_language_mode: properties %
#  %ccm_git_file_type: text/plain %
#  %ccm_git_file_encoding: us-ascii %
#  %ccm_git_file_eol: CRLF %
#  %ccm_git_exec: no %
#  %ccm_git_size: 925 %
#  TermiteTowers Continuous Code Management Header TEMPLATE --- %ccm_git_header_end:  %  
# %git_commit_history: 2026-06-10 mpegg  june bulk update  % 

map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

server {
    listen 3261 ssl;
    server_name pics.justanotherhuman.ca memorylab.analacres.ca;

    ssl_certificate     /etc/letsencrypt/live/memorylab.analacres.ca/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/memorylab.analacres.ca/privkey.pem;

    client_max_body_size 50000M;
    proxy_request_buffering off;
    client_body_buffer_size 1024k;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    proxy_http_version 1.1;
    proxy_redirect off;
    proxy_read_timeout 600s;
    proxy_send_timeout 600s;

    location / {
        proxy_pass http://127.0.0.1:3370/;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
    }
}
