#  TermiteTowers Continuous Code Management Header TEMPLATE --- %ccm_git_header_start:  %
#  %ccm_git_repo: TermiteTowers %
#  %ccm_git_branch: dev1 %
#  %ccm_git_object_id: infra/nginx/sites-available/kuma.conf:139 %
#  %ccm_git_author: mpegg %
#  %ccm_git_author_email: mpegg@hotmail.com %
#  %ccm_git_blob_sha: 90478bbf0bdf2fcceab29b2db413fc98f92acf40 %
#  %ccm_git_commit_id: 4b7c4d5292241b4ba1eb82f1b2ec0509b8fd544f %
#  %ccm_git_commit_count: 139 %
#  %ccm_git_commit_date: 2026-03-22 09:03:20 -0400 %
#  %ccm_git_commit_author: mpegg %
#  %ccm_git_commit_email: mpegg@hotmail.com %
#  %ccm_git_commit_message: march updates %
#  %ccm_git_modify_date: 2026-03-22 09:03:21 %
#  %ccm_git_file_last_modified: 2026-03-22 09:03:21 %
#  %ccm_git_file_name: kuma.conf %
#  %ccm_git_path: infra/nginx/sites-available/kuma.conf %
#  %ccm_git_language_mode: properties %
#  %ccm_git_file_type: text/plain %
#  %ccm_git_file_encoding: us-ascii %
#  %ccm_git_file_eol: CRLF %
#  %ccm_git_exec: no %
#  %ccm_git_size: 807 %
#  TermiteTowers Continuous Code Management Header TEMPLATE --- %ccm_git_header_end:  %  
# %git_commit_history: unknown  unknown  unknown  % 
# %git_commit_history: 2025-10-10 mpegg  big update  % 

server {
    listen 80;
    server_name kuma.termitetowers.ca;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name kuma.termitetowers.ca;

    ssl_certificate     /etc/letsencrypt/live/termitetowers.ca-0001/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/termitetowers.ca-0001/privkey.pem;

    location / {
        proxy_pass http://localhost:3700/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
