version: '3.8'

services:
  whisper-faster:
    image: nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04
    container_name: whisper-faster-dev1
    working_dir: /app
    volumes:
      - ../source:/app
      - ../audio:/app/audio
      - ../output:/app/output
      - /mnt/ai_storage/models/whisper:/app/models
      - /mnt/ai_storage/models/huggingface:/root/.cache/huggingface
      - /mnt/ai_storage/models/pip:/root/.cache/pip
      - /mnt/ai_storage/models/torch:/root/.cache/torch
    command: >
      bash -c "apt-get update &&
               apt-get install -y python3.10 python3.10-venv python3.10-dev python3-pip git ffmpeg libsndfile1 &&
               update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 1 &&
               python3 -m pip install --upgrade pip &&
               python3 -m pip install torch torchvision torchaudio &&
               python3 -m pip install faster-whisper &&
               python3 /app/transcribe.py --input_dir /app/audio --output_dir /app/output --model_dir /app/models --model_size medium --device cuda --compute_type float16"
    environment:
      - PYTHONUNBUFFERED=1
      - HF_HOME=/root/.cache/huggingface
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]


Get:1 http://archive.ubuntu.com/ubuntu jammy InRelease [270 kB]
whisper-faster-dev1  | Get:2 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
whisper-faster-dev1  | Get:3 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease [1581 B]
whisper-faster-dev1  | Err:3 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
whisper-faster-dev1  |   Couldn't create temporary file /tmp/apt.conf.Rdwaf0 for passing config to apt-key
whisper-faster-dev1  | Err:1 http://archive.ubuntu.com/ubuntu jammy InRelease
whisper-faster-dev1  |   Couldn't create temporary file /tmp/apt.conf.eC8Xpp for passing config to apt-key
whisper-faster-dev1  | Get:4 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
whisper-faster-dev1  | Err:2 http://security.ubuntu.com/ubuntu jammy-security InRelease
