# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  tdarr-node:
    image: ghcr.io/haveagitgat/tdarr_node:latest
    container_name: tdarr-node-dev1
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=${TZ:-America/Toronto}
      - PUID=${PUID:-2001}
      - PGID=${PGID:-1006}
      - nodeName=${TDARR_NODE_NAME:-monolith-node}
      - tdarrServerIP=${TDARR_SERVER_IP:-192.168.4.63}
      - tdarrServerPort=${TDARR_SERVER_PORT:-8266}
      - serverIP=${TDARR_SERVER_IP:-192.168.4.63}
      - serverPort=${TDARR_SERVER_PORT:-8266}
      - ffmpegVersion=static
      - npmPackages=false
      - videoProcessors=${TDARR_VIDEO_PROCS:-1}
      - nodeWorkerThreads=${TDARR_WORKERS:-1}
    volumes:
      # Local self-contained mounts
      - ./config:/app/configs
      - ./logs:/app/logs
      - ./cache:/temp
      # Media path used for processing (edit to match your environment)
      - /mnt/media:/mnt/media:rw
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "5"
