# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
# TermiteTowers Continuous Code Management Header TEMPLATE
# % ccm_modify_date: 2025-08-31 14:31:46 %
# % ccm_author: mpegg %
# % ccm_author_email: mpegg@hotmail.com %
# % ccm_repo: https://github.com/mpegg007/TermiteTowers.git %
# % ccm_branch: dev1 %
# % ccm_object_id: infra/tdarr-node/tdarr-node-dev1.nvidia.yml:0 %
# % ccm_commit_id: unknown %
# % ccm_commit_count: 0 %
# % ccm_commit_message: unknown %
# % ccm_commit_author: unknown %
# % ccm_commit_email: unknown %
# % ccm_commit_date: 1970-01-01 00:00:00 +0000 %
# % ccm_file_last_modified: 2025-08-31 14:30:32 %
# % ccm_file_name: tdarr-node-dev1.nvidia.yml %
# % ccm_file_type: text/plain %
# % ccm_file_encoding: us-ascii %
# % ccm_file_eol: CRLF %
# % ccm_path: infra/tdarr-node/tdarr-node-dev1.nvidia.yml %
# % ccm_blob_sha: 7fc3dbf5b793dc4b7525a59cd7ca3abc0c35d42b %
# % ccm_exec: no %
# % ccm_size: 1181 %
# % ccm_tag:  %
# tt-ccm.header.end
services:
  tdarr-node:
    # NVIDIA GPU overlay. Use with: docker compose -f tdarr-node-dev1.yml -f tdarr-node-dev1.nvidia.yml up -d
    gpus: all
