#  TermiteTowers Continuous Code Management Header TEMPLATE --- %ccm_git_header_start:  %
#  %ccm_git_repo: TermiteTowers %
#  %ccm_git_branch: dev1 %
#  %ccm_git_object_id: infra/dhcp/configs/kea/kea-ctrl-agent.conf:0 %
#  %ccm_git_author: mpegg %
#  %ccm_git_author_email: mpegg@hotmail.com %
#  %ccm_git_blob_sha: 2becf2acab61f08f89b3b6d1510fb6b3ff5e923d %
#  %ccm_git_commit_id: unknown %
#  %ccm_git_commit_count: 0 %
#  %ccm_git_commit_date: 1970-01-01 00:00:00 +0000 %
#  %ccm_git_commit_author: unknown %
#  %ccm_git_commit_email: unknown %
#  %ccm_git_commit_message: unknown %
#  %ccm_git_modify_date: 2025-09-27 11:12:09 %
#  %ccm_git_file_last_modified: 2025-09-23 19:59:07 %
#  %ccm_git_file_name: kea-ctrl-agent.conf %
#  %ccm_git_path: infra/dhcp/configs/kea/kea-ctrl-agent.conf %
#  %ccm_git_language_mode: properties %
#  %ccm_git_file_type: application/json %
#  %ccm_git_file_encoding: us-ascii %
#  %ccm_git_file_eol: CRLF %
#  %ccm_git_exec: no %
#  %ccm_git_size: 689 %
#  TermiteTowers Continuous Code Management Header TEMPLATE --- %ccm_git_header_end:  %  
{
    "Control-agent": {
        "http-host": "0.0.0.0",
        "http-port": 8080,
        "control-sockets": {
            "dhcp4": {
                "socket-type": "unix",
                "socket-name": "/var/run/kea/kea4-ctrl-socket"
            }
        },
        "loggers": [
            {
                "name": "kea-ctrl-agent",
                "output_options": [
                    {
                        "output": "/var/log/kea/kea-ctrl-agent.log",
                        "maxsize": 10485760,
                        "maxver": 5
                    }
                ],
                "severity": "INFO",
                "debuglevel": 0
            }
        ]
    }
}
